In [1]:
import numpy as np  
import pandas as pd 
import math
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


from sklearn import decomposition
from sklearn import datasets
%matplotlib inline

In [2]:
dataset = pd.read_csv("../../crimesInChicagoData/dataset.csv")

In [4]:
dataset.head()

,Unnamed: 0,Unnamed: 0.1,ID,Date,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,District,FBI Code,Year,Latitude,Longitude
0,0,0,4786321,2004-01-01 00:01:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,4.0,06,2004.0,41.734106,-87.563621
1,1,1,4676906,2003-03-01 00:00:00,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,9.0,26,2003.0,41.817229,-87.637328
2,2,2,4789749,2004-06-20 11:00:00,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,14.0,20,2004.0,41.915620,-87.694019
3,3,3,4789765,2004-12-30 20:00:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,False,25.0,06,2004.0,41.919054,-87.752178
4,4,4,4677901,2003-05-01 01:00:00,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,22.0,06,2003.0,41.691785,-87.635116

In [5]:
dataset = dataset.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis = 1)

In [6]:
dataset.head()

,ID,Date,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,District,FBI Code,Year,Latitude,Longitude
0,4786321,2004-01-01 00:01:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,4.0,06,2004.0,41.734106,-87.563621
1,4676906,2003-03-01 00:00:00,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,9.0,26,2003.0,41.817229,-87.637328
2,4789749,2004-06-20 11:00:00,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,14.0,20,2004.0,41.915620,-87.694019
3,4789765,2004-12-30 20:00:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,False,25.0,06,2004.0,41.919054,-87.752178
4,4677901,2003-05-01 01:00:00,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,22.0,06,2003.0,41.691785,-87.635116

In [7]:
def changeToDateTime(df, columnName, timeFormat): 
    df[columnName] = pd.to_datetime(df[columnName], format = timeFormat)

In [8]:
changeToDateTime(dataset, 'Date', '%Y-%m-%d %H:%M:%S')

In [9]:
days = dataset['Date'].apply(lambda x: x.day)

In [10]:
hours = dataset['Date'].apply(lambda x: x.hour)

In [11]:
months = dataset['Date'].apply(lambda x: x.month)

In [12]:
hoursDf = pd.DataFrame({'Hours': hours})
monthsDf = pd.DataFrame({'Months': months})
daysDf = pd.DataFrame({'Days': days})

In [14]:
dataset = pd.concat([dataset, monthsDf, hoursDf, daysDf], axis = 1)

In [15]:
dataset.head()

,ID,Date,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,District,FBI Code,Year,Latitude,Longitude,Months,Hours,Days
0,4786321,2004-01-01 00:01:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,4.0,06,2004.0,41.734106,-87.563621,1,0,1
1,4676906,2003-03-01 00:00:00,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,9.0,26,2003.0,41.817229,-87.637328,3,0,1
2,4789749,2004-06-20 11:00:00,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,14.0,20,2004.0,41.915620,-87.694019,6,11,20
3,4789765,2004-12-30 20:00:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,False,25.0,06,2004.0,41.919054,-87.752178,12,20,30
4,4677901,2003-05-01 01:00:00,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,22.0,06,2003.0,41.691785,-87.635116,5,1,1

In [16]:
dataset.to_csv("../../crimesInChicagoData/expandedDateInfo.csv")

In [2]:
dataset = pd.read_csv("../../crimesInChicagoData/expandedDateInfo.csv")

In [3]:
dataset.head()

,Unnamed: 0,ID,Date,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,District,FBI Code,Year,Latitude,Longitude,Months,Hours,Days
0,0,4786321,2004-01-01 00:01:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,4.0,06,2004.0,41.734106,-87.563621,1,0,1
1,1,4676906,2003-03-01 00:00:00,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,9.0,26,2003.0,41.817229,-87.637328,3,0,1
2,2,4789749,2004-06-20 11:00:00,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,14.0,20,2004.0,41.915620,-87.694019,6,11,20
3,3,4789765,2004-12-30 20:00:00,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,False,25.0,06,2004.0,41.919054,-87.752178,12,20,30
4,4,4677901,2003-05-01 01:00:00,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,22.0,06,2003.0,41.691785,-87.635116,5,1,1

In [4]:

from kmodes.kmodes import KModes

In [5]:
km = KModes(n_clusters=4, init = "Huang", n_init = 1, verbose=1)

In [6]:
dataset = dataset.drop(['ID', 'Date'], axis = 1)

In [7]:
dataset.head()

,Unnamed: 0,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,District,FBI Code,Year,Latitude,Longitude,Months,Hours,Days
0,0,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,4.0,06,2004.0,41.734106,-87.563621,1,0,1
1,1,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,9.0,26,2003.0,41.817229,-87.637328,3,0,1
2,2,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,14.0,20,2004.0,41.915620,-87.694019,6,11,20
3,3,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,False,25.0,06,2004.0,41.919054,-87.752178,12,20,30
4,4,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,22.0,06,2003.0,41.691785,-87.635116,5,1,1

In [8]:
year2001 = dataset.loc[dataset['Year'] == 2001.0]

In [9]:
clusters = km.fit_predict(year2001)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 203225, cost: 5410208.0
Run 1, iteration: 2/100, moves: 8185, cost: 5410208.0

In [10]:
print(clusters)
print(len(clusters))
print(len(year2001))

[1 0 2 ..., 1 2 0]
568517
568517

In [11]:
km.labels_

array([1, 0, 2, ..., 1, 2, 0], dtype=uint8)

In [12]:
km.cluster_centroids_

array([['17', '0460', 'BATTERY', 'SIMPLE', 'STREET', 'False', 'False',
        '8.0', '08B', '2001.0', '41.976200173', '-87.905312411', '1', '22',
        '19'],
       ['6', '1310', 'CRIMINAL DAMAGE', 'TO PROPERTY', 'RESIDENCE',
        'False', 'False', '6.0', '14', '2001.0', '41.750828225999996',
        '-87.625182794', '2', '12', '14'],
       ['18', '0820', 'THEFT', '$500 AND UNDER', 'STREET', 'False',
        'False', '18.0', '06', '2001.0', '41.976200173', '-87.905312411',
        '7', '21', '7'],
       ['20', '2027', 'NARCOTICS', 'POSS: CRACK', 'STREET', 'True',
        'False', '2.0', '18', '2001.0', '41.862118973', '-87.693823763',
        '1', '19', '6']],
      dtype='<U32')

In [34]:
clustersdf = pd.DataFrame(clusters)

In [35]:
clustersdf

        0
0       1
1       0
2       2
3       3
4       1
5       2
6       2
7       0
8       1
9       2
10      3
11      1
12      1
13      2
14      1
15      2
16      2
17      0
18      1
19      2
20      2
21      1
22      2
23      2
24      2
25      2
26      2
27      1
28      3
29      2
...    ..
568487  2
568488  2
568489  2
568490  1
568491  0
568492  2
568493  0
568494  1
568495  0
568496  0
568497  0
568498  1
568499  0
568500  1
568501  2
568502  2
568503  0
568504  0
568505  0
568506  0
568507  2
568508  3
568509  1
568510  0
568511  0
568512  2
568513  2
568514  1
568515  2
568516  0

[568517 rows x 1 columns]

In [23]:
clustersdf.loc[clustersdf[0] == 1].sum()

0    113877
dtype: int64

In [24]:
clustersdf.loc[clustersdf[0] == 2].sum()

0    268914
dtype: int64

In [25]:
clustersdf.loc[clustersdf[0] == 3].sum()

0    282867
dtype: int64

In [27]:
len(clustersdf)

568517

In [47]:
clustersdf.columns = ['clusters']
clustersdf

        clusters
0              1
1              0
2              2
3              3
4              1
5              2
6              2
7              0
8              1
9              2
10             3
11             1
12             1
13             2
14             1
15             2
16             2
17             0
18             1
19             2
20             2
21             1
22             2
23             2
24             2
25             2
26             2
27             1
28             3
29             2
...          ...
568487         2
568488         2
568489         2
568490         1
568491         0
568492         2
568493         0
568494         1
568495         0
568496         0
568497         0
568498         1
568499         0
568500         1
568501         2
568502         2
568503         0
568504         0
568505         0
568506         0
568507         2
568508         3
568509         1
568510         0
568511         0
568512         2
568513         2
568514         1
568515         2
568516         0

[568517 rows x 1 columns]

In [50]:
year2001 = year2001.reset_index()

In [55]:
year2001New = pd.concat([year2001, clustersdf], axis = 1)

In [56]:
year2001New

,index,Unnamed: 0,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,District,FBI Code,Year,Latitude,Longitude,Months,Hours,Days,clusters
0,6,6,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,True,5.0,02,2001.0,41.687020,-87.608445,1,11,1,1
1,17,17,1753,OFFENSE INVOLVING CHILDREN,SEX ASSLT OF CHILD BY FAM MBR,RESIDENCE,True,False,8.0,02,2001.0,41.791519,-87.729099,1,0,1,0
2,18,18,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,False,9.0,06,2001.0,41.834523,-87.682642,1,0,1,2
3,20,20,1754,OFFENSE INVOLVING CHILDREN,AGG SEX ASSLT OF CHILD FAM MBR,RESIDENCE,True,False,7.0,02,2001.0,41.778540,-87.674036,6,8,16,3
4,25,25,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,15.0,17,2001.0,41.896809,-87.762472,6,8,1,1
5,32,32,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,True,14.0,06,2001.0,41.921795,-87.713269,7,10,25,2
6,33,33,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,7.0,06,2001.0,41.772187,-87.638570,6,20,23,2
7,50,50,0842,THEFT,AGG: FINANCIAL ID THEFT,OTHER,False,False,8.0,06,2001.0,41.748448,-87.679203,1,0,1,0
8,63,63,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,4.0,20,2001.0,41.657828,-87.544575,5,0,1,1
9,118,118,0842,THEFT,AGG: FINANCIAL ID THEFT,RESIDENCE,False,False,7.0,06,2001.0,41.774876,-87.636719,10,0,1,2
10,130,130,0265,CRIM SEXUAL ASSAULT,AGGRAVATED: OTHER,RESIDENCE,True,False,22.0,02,2001.0,41.694893,-87.635364,1,0,1,3
11,131,131,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,6.0,06,2001.0,41.744169,-87.610034,10,8,1,1
12,132,132,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,RESIDENCE,False,False,12.0,11,2001.0,41.897565,-87.676027,11,9,9,1
13,133,133,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,22.0,06,2001.0,41.690746,-87.706746,5,15,30,2
14,135,135,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,15.0,06,2001.0,41.889244,-87.750622,6,12,1,1
15,138,138,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,25.0,06,2001.0,41.908495,-87.722688,1,0,1,2
16,150,150,0840,THEFT,FINANCIAL ID THEFT: OVER $300,APARTMENT,False,False,10.0,06,2001.0,41.860327,-87.730966,8,12,1,2
17,252,252,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,HOTEL/MOTEL,False,False,1.0,26,2001.0,41.884594,-87.624607,8,0,31,0
18,254,254,1753,OFFENSE INVOLVING CHILDREN,SEX ASSLT OF CHILD BY FAM MBR,RESIDENCE,False,True,25.0,02,2001.0,41.935694,-87.744451,3,9,1,1
19,260,260,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,BANK,False,True,9.0,11,2001.0,41.808723,-87.664237,7,0,1,2
20,266,266,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,1.0,06,2001.0,41.852793,-87.628049,7,0,1,2
21,276,276,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,RESIDENCE,False,False,11.0,11,2001.0,41.896226,-87.735830,10,0,1,1
22,286,286,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,7.0,06,2001.0,41.775186,-87.637211,8,9,26,2
23,289,289,0840,THEFT,FINANCIAL ID THEFT: OVER $300,STREET,False,False,8.0,06,2001.0,41.811805,-87.746596,2,0,1,2
24,292,292,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,9.0,06,2001.0,41.811615,-87.701501,11,0,1,2
25,294,294,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,8.0,06,2001.0,41.782136,-87.686315,9,0,10,2
26,298,298,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,True,7.0,06,2001.0,41.783467,-87.646640,6,9,1,2
27,303,303,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,8.0,06,2001.0,41.797864,-87.764752,8,12,1,1
28,305,305,1140,DECEPTIVE PRACTICE,EMBEZZLEMENT,"SCHOOL, PRIVATE, GROUNDS",True,False,24.0,12,2001.0,42.001679,-87.660604,1,12,1,3
29,325,325,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,25.0,06,2001.0,41.921278,-87.775776,1,9,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568487,1923363,1923363,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,3.0,06,2001.0,41.766159,-87.621858,12,0,28,2
568488,1923366,1923366,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,8.0,06,2001.0,41.774379,-87.696786,12,0,1,2
568489,1923373,1923373,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,17.0,06,2001.0,41.941162,-87.725876,12,0,1,2
568490,1923374,1923374,1754,OFFENSE INVOLVING CHILDREN,AGG SEX ASSLT OF CHILD FAM MBR,RESIDENCE,True,True,17.0,02,2001.0,41.961358,-87.698605,6,20,18,1
568491,1923375,1923375,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,8.0,17,2001.0,41.800961,-87.734262,5,23,20,0
568492,1923378,1923378,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,20.0,06,2001.0,41.979383,-87.695359,6,8,1,2
568493,1923402,1923402,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,True,12.0,17,2001.0,41.880340,-87.672350,1,23,1,0
568494,1923425,1923425,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,True,True,18.0,20,2001.0,41.902862,-87.636098,4,0,13,1
568495,1923426,1923426,0560,ASSAULT,SIMPLE,RESIDENCE,False,False,22.0,08A,2001.0,41.708616,-87.658509,1,12,26,0
568496,1923428,1923428,0620,BURGLARY,UNLAWFUL ENTRY,RESIDENCE-GARAGE,False,False,8.0,05,2001.0,41.737600,-87.714952,1,14,9,0
568497,1923429,1923429,0460,BATTERY,SIMPLE,STREET,False,False,15.0,08B,2001.0,41.880479,-87.755134,2,12,8,0
568498,1923430,1923430,1310,CRIMINAL DAMAGE,TO PROPERTY,COMMERCIAL / BUSINESS OFFICE,False,False,24.0,14,2001.0,42.006178,-87.665127,3,10,13,1
568499,1923431,1923431,041A,BATTERY,AGGRAVATED: HANDGUN,STREET,False,False,15.0,04B,2001.0,41.880479,-87.755134,4,23,12,0
568500,1923432,1923432,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,8.0,14,2001.0,41.737600,-87.714952,5,23,19,1
568501,1923433,1923433,0820,THEFT,$500 AND UNDER,STREET,False,False,12.0,06,2001.0,41.896990,-87.656396,7,4,15,2
568502,1923434,1923434,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,False,False,15.0,03,2001.0,41.880479,-87.755134,7,4,15,2
568503,1923435,1923435,5001,OTHER OFFENSE,OTHER CRIME INVOLVING PROPERTY,STREET,False,False,15.0,26,2001.0,41.880479,-87.755134,9,16,1,0
568504,1923436,1923436,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,False,False,15.0,03,2001.0,41.880479,-87.755134,11,11,6,0
568505,1923437,1923437,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,8.0,05,2001.0,41.737600,-87.714952,11,14,9,0
568506,1923438,1923438,0460,BATTERY,SIMPLE,SIDEWALK,True,True,15.0,08B,2001.0,41.880479,-87.755134,12,19,16,0
568507,1923439,1923439,0820,THEFT,$500 AND UNDER,STREET,False,False,15.0,06,2001.0,41.880479,-87.755134,12,21,23,2
568508,1923454,1923454,0261,CRIM SEXUAL ASSAULT,AGGRAVATED: HANDGUN,RESIDENCE PORCH/HALLWAY,True,False,4.0,02,2001.0,41.750369,-87.568503,3,20,10,3
568509,1923476,1923476,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,8.0,06,2001.0,41.775545,-87.794421,5,12,15,1
568510,1923481,1923481,1754,OFFENSE INVOLVING CHILDREN,AGG SEX ASSLT OF CHILD FAM MBR,RESIDENCE,False,False,25.0,02,2001.0,41.910820,-87.716722,1,0,1,0
568511,1923486,1923486,1753,OFFENSE INVOLVING CHILDREN,SEX ASSLT OF CHILD BY FAM MBR,RESIDENCE,False,False,2.0,02,2001.0,41.807275,-87.593707,1,0,1,0
568512,1923492,1923492,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,20.0,06,2001.0,41.970614,-87.670922,1,0,1,2
568513,1923498,1923498,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,3.0,06,2001.0,41.762408,-87.599211,3,0,31,2
568514,1923503,1923503,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,8.0,06,2001.0,41.788037,-87.698249,8,12,15,1
568515,1923509,1923509,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,ALLEY,False,False,25.0,06,2001.0,41.922997,-87.757492,4,9,1,2
568516,1923512,1923512,0610,BURGLARY,FORCIBLE ENTRY,OTHER,False,False,4.0,05,2001.0,41.736343,-87.555413,6,0,4,0